name: Notebook generator CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get install texlive texlive-latex-extra
        cd "./Notebook Generator"
        sudo npm install
        cd ..
    - name: Generate Notebook
      run: |
        mkdir Output
        cd "./Notebook Generator"
        ./bin/notebookgen ./../Template/ --author "BUET Sommohito" --columns 3 --paper a4paper --size 10 --output ./../Output/codes.pdf
        cd ..
        cd ./Notes
        pdflatex main.tex
        cp ./main.pdf ../Output/notes.pdf
        cd ..
    - name: Upload Generated Notebook
      uses: actions/upload-artifact@v4
      with:
          name: notebook
          path: |
            ./Output/codes.pdf
            ./Notes/notes.pdf
          compression-level: 0  # no compression
          if-no-files-found: error