name: Notebook generator CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get install texlive texlive-latex-extra
        cd "./Notebook Generator"
        sudo npm install
        cd ..
    - name: Generate Notebook
      run: |
        cd "./Notebook Generator"
        ./bin/notebookgen ./../Template/ --author "BUET Sommohito" --columns 3 --paper a4paper --size 10
    - name: Upload Generated Notebook
      uses: actions/upload-artifact@v4
      with:
          name: notebook.pdf
          path: ./Notebook Generator/notebook.pdf